
var products = [
    {
        id: 1,
        name: "Isis",
        desc_short: "Perfect with your favorite tortilla chips, this delicious Corn Salsa is amazing! Loaded with fresh, delicious veggies, this salsa is just as flavorful as it is pretty.",
        desc_long: "<p>Isis is the Egyptian Goddess of marriage, fertility, motherhood, magic, medicine, and harvest. She taught human woman how to grind and store corn, spin flax, and weave cloth. Our corn salsa is packed full of flavor bringing you back for more, like magic.</p><p>Perfect with your favorite tortilla chips, this delicious Corn Salsa is amazing! Loaded with fresh, delicious veggies, this salsa is just as flavorful as it is pretty.</p> ",
        image_small: "images/corn-salsa.jpeg",
        image_large: "images/corn-salsa.jpeg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 7.00,
        price_previous:10.00,
        onSale: true,
        volume: "8 oz",
        style: ["mild"],
        popular: true,
        rating: 4.9,
        featured: true

    },
    {
        id: 2,
        name: "Aphrodite",
        desc_short: "Our Mango Salsa is a delicious combination of sweet juicy mangoes, tart lime juice and peppers for the perfect combination of sweet and heat.",
        desc_long: "<p>The Greek Goddess of love, beauty, pleasure, and passion. With our mango salsa you will find yourself falling in love with each bite, sparking simply passions of pleasure.</p><p>Our Mango Salsa is a delicious combination of sweet juicy mangoes, tart lime juice and peppers for the perfect combination of sweet and heat.</p>",
        image_small: "images/mango-salsa-6.jpeg",
        image_large: "images/mango-salsa-6.jpeg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 10.00,
        price_previous:10.00,
        onSale: false,
        volume: "8 oz",
        style: ["mild", "sweet"],
        popular: false,
        rating: 4.9,
        featured: true
    },
    {
        id: 3,
        name: "Ostara",
        desc_short: "Our Pineapple Salsa is bright and colorful full of vibrant ingredients. Bringing the freshness of spring with every bite, bursting with unexpecting flavors.",
        desc_long: "<p>Ostara is the Germanic Goddess of spring where she oversees the budding plants and burgeoning fertility of the earth. She also symbolizes the festive enjoyment of nature.</p><p>Our Pineapple Salsa is bright and colorful full of vibrant ingredients. Bringing the freshness of spring with every bite, bursting with unexpecting flavors.</p>",
        image_small: "images/pinapple-salsa-2a.jpg",
        image_large: "images/pinapple-salsa-2a.jpg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 9.00,
        price_previous:12.00,
        onSale: true,
        volume: "8 oz",
        style: ["mild", "sweet"],
        popular: true,
        rating: 4.7,
        featured: true
    },
    {
        id: 4,
        name: "Zorya",
        desc_short: "This salsa starts with a sweet earthy flavor, going to the bright citrus notes, and finishing with the heat of the peppers.",
        desc_long: "<p>There are three Slavic Dawn Goddesses; Morning Star, Evening Star, and Midnight Star. This salsa embraces all three, starting with a sweet earthy flavor in the morning, going to the bright citrus notes in the evening, finally finishing with the heat of the peppers at midnight.</p><p>This salsa is simply a wonderful experience to savor and enjoy on any occasion!</p>",
        image_small: "images/hot-salsa-verde.jpeg",
        image_large: "images/hot-salsa-verde.jpeg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 10.00,
        price_previous:10.00,
        onSale: false,
        volume: "8 oz",
        style: ["hot", "sweet"],
        popular: false,
        rating: 4.9,
        featured: false
    },
    {
        id: 5,
        name: "Pele",
        desc_short: "Known for it's fiery temperament, this salsa starts with earthy savory notes turning straight to fiery finish.",
        desc_long: "<p>The Hawaiian Goddess of volcanoes and fire. Known for her fiery temperament as well as being the creator of Hawaii.</p><p>Much like it's namesake, our Pele Salsa is known for it's fiery temperament, this salsa starts with earthy savory notes turning straight to fiery finish.",
        image_small: "images/haberno-salsa-verde-2.jpg",
        image_large: "images/haberno-salsa-verde-2.jpg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 10.00,
        price_previous:10.00,
        onSale: false,
        volume: "8 oz",
        style: ["hot"],
        popular: true,
        rating: 4.8,
        featured: false
    },
    {
        id: 6,
        name: "Demeter",
        desc_short: "Bringing simple ingredients together to create a delicious and healthy dish that's welcome on any table.",
        desc_long: "<p>The Greek Goddess of harvest, grain, and fertility. Pico de Gallo is a beautiful way to respect our harvests each season - bringing simple ingredients together to create a delicious dish.  </p><p>Our Demeter Salsa brings simple ingredients together to create a delicious and healthy dish that's welcome on any table.</p>",
        image_small: "images/Pico-de-Gallo.jpg",
        image_large: "images/Pico-de-Gallo.jpg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 10.00,
        price_previous:10.00,
        onSale: false,
        volume: "8 oz",
        style: ["mild"],
        popular: false,
        rating: 4.7,
        featured: false
    },
    {
        id: 7,
        name: "Pachamama",
        desc_short: "The complex yet smooth salsa is sweet and spicy  - perfect as a dip or glazing chicken or anything really.",
        desc_long: "<p>Pachamama is an Incan fertility goddess who presides over planting and harvesting, embodies the mountains, and taught humans how to make beer.</p><p>The complex yet smooth salsa is sweet and spicy  - perfect as a dip or glazing chicken or anything really.</p>",
        image_small: "images/mango-salsa-7.jpg",
        image_large: "images/mango-salsa-7.jpg",
        image_details: ["images/corn-salsa-530x462.jpg", "images/corn-salsa-2-530x462.jpg","images/corn-salsa-5-530x462.jpg"],
        price_current: 10.00,
        price_previous:10.00,
        onSale: false,
        volume: "8 oz",
        style: ["mild", "sweet"],
        popular: false,
        rating: 4.9,
        featured: true
    }
];